services:
  users-api:
    # image: users
    build:
      context: .
      # dockerfile: Dockerfile
      target: api-dev
    ports:
      - 3001:3001
    links:
      - mondongo
    volumes:
      - .:/home/app
    develop:
      watch:
        - path: ./src
          action: sync
          target: /home/app/dist
    environment:
      - PORT=${PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
    env_file:
      - .env
    depends_on:
      mondongo:
        condition: service_healthy
  mondongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
      # - mysql-data:/var/lib/mysql
      # - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "mongosh --eval 'db.runCommand({ ping: 1 })' --quiet"
      interval: 10s
      timeout: 10s
      retries: 5
      start_interval: 5s
volumes:
  mongo-data:
